name: flutter_media_session
description: "A simple plugin to play/pause media session on Android devices."
version: 0.1.0

platforms:
  android:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  personal_flutter_lints:
    git:
      url: https://github.com/ArunPrakashG/personal_flutter_lints.git
      ref: main

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.synnetic.flutter_media_session
        pluginClass: FlutterMediaSessionManagerPlugin
